# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
