# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='url_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Source'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
