# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170602_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='url_logo',
            field=models.URLField(max_length=500),
        ),
    ]
