# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170531_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='paper',
            new_name='source',
        ),
    ]
