# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170531_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content_len',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
