# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
