# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20170602_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
