# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170601_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url_logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
