# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170615_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-ranking']},
        ),
        migrations.AddField(
            model_name='topic',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
