# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170601_1806'),
        ('topics', '0003_auto_20170601_1247'),
    ]

    operations = [
    ]
