# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_article_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
