# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170602_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='topics',
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
            preserve_default=False,
        ),
    ]
