# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0005_auto_20170616_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('subscribers', models.ManyToManyField(related_name='tag_subscriber', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
