# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20170606_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Source'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
