# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_merge_20170601_1915'),
        ('topics', '0006_remove_topic_title'),
    ]

    operations = [
    ]
