# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='topic_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
