# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_tag_topic_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-topic_count']},
        ),
    ]
