# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20170619_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['bias']},
        ),
        migrations.AddField(
            model_name='article',
            name='bias',
            field=models.FloatField(default=0),
        ),
    ]
