# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_remove_topic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
