# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_topic_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
