# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='FactReaction',
        ),
    ]
