# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170602_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias_percent', models.FloatField()),
                ('fact_percent', models.FloatField()),
                ('fake_percent', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Article')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighlightedReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('content', models.TextField()),
                ('content_end', models.PositiveIntegerField()),
                ('reaction', models.IntegerField(choices=[(1, 'Bias'), (2, 'Fact'), (3, 'Fake')])),
                ('comment', models.CharField(blank=True, max_length=140)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Article')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
