# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereaction',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='highlightedreaction',
            name='topic',
        ),
    ]
