# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20170607_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightedreaction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='highlightedreaction',
            name='owner',
        ),
        migrations.DeleteModel(
            name='HighlightedReaction',
        ),
    ]
