# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metric_content_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
