# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170602_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0002_auto_20170606_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereaction',
            unique_together=set([('owner', 'article')]),
        ),
    ]
