# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20170531_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metric',
            new_name='Reaction',
        ),
    ]
