# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20170613_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlereaction',
            old_name='bias_percent',
            new_name='bias',
        ),
        migrations.RemoveField(
            model_name='articlereaction',
            name='fact_percent',
        ),
        migrations.RemoveField(
            model_name='articlereaction',
            name='fake_percent',
        ),
    ]
