# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20170614_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereaction',
            unique_together=set([]),
        ),
    ]
