# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alignment',
        ),
        migrations.AddField(
            model_name='profile',
            name='political_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='political_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
