# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20170615_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
