# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170619_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifiedusers',
            name='id',
        ),
        migrations.AddField(
            model_name='notifiedusers',
            name='id_key',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
